config/routes.rb
Rails.application.routes.draw do
  get 'bookings/view_seat'
  get 'bookings/allocate_seat'
  resources :seat_configurations
  resources :passenger_bookings
  resources :passengers
  resources :bookings
  resources :flights
  resources :airports
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  get 'homes/index'
  root "homes#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/flight.rb
class Flight < ApplicationRecord
	belongs_to :from_airport, class_name: 'Airport', foreign_key: :departure_airport_id
	belongs_to :to_airport, class_name: 'Airport', foreign_key: :destination_airport_id
	has_many :seat_configurations
	has_many :bookings

	validates :departure_airport_id, exclusion: { in: lambda{ |flight| [flight.destination_airport_id] } }
	validate :flight_time_today_or_future, on: :create
	validates :flight_time, presence: true
	



	#enum category: [:first_class, :business_class, :economy_class]

	@@blocked_seats = 0
	FLIGHT_MAP = {"first_class" => 'f', "business_class" => 'b', "economy_class" => 'e'}

	def self.update_blocked_seats(updater)
		@@blocked_seats += updater
	end

	def self.blocked_seats
		@@blocked_seats
	end
	
	def availability
		bookings.inject(0) do |count, booking|
			count + booking.passenger_bookings.count
		end + Flight.blocked_seats
	end

	#FLIGHT MAP
	# [
	  #   'fe_ff',
	  #   'ff_ff',
	  #   'ee_ee',
	  #   'ee_ee',
	  #   'ee___',
	  #   'ee_ee',
	  #   'ee_ee',
	  #   'ee_ee',
	  #   'eeeee',
	  # ]
	  # f stands first class
	  # e stands for economy
	  # b for business
	  # _ for space

	#BOOKED SEATS
	#['1_2', '4_1', '7_1', '7_2'] row_seat


	def generate_seat_availabilty_ui
		Rails.cache.fetch("Flight_#{id}_map") do
			puts 'evaluating...' ; 
			all_flight_bookings = bookings.map(&:passenger_bookings).flatten.compact
			allocated_booking_map = all_flight_bookings.select {|booking| booking.seat_number?}.map(&:seat_number)
			flight_map = []
			seat_configurations.each do |conf|
				conf.no_of_rows.times {flight_map << (FLIGHT_MAP[conf.category.gsub(' ', '_').downcase] * conf.seat_in_row)}
			end
			{allocated: allocated_booking_map, flight_map: flight_map}
		end
	end

	def self.get_flight_from_pnr(pnr)
		find(pnr[1..4].to_i)
	end

	def self.search(from, to, date)
	  where(departure_airport_id: from, destination_airport_id: to, flight_time: Flight.format_date(date))
	end

	def self.format_date(date)
	  date = Date.strptime(date, '%m/%d/%y')
	  date.beginning_of_day..date.end_of_day
	end

	private
	def flight_time_today_or_future
		return if flight_time && flight_time >= Date.today
	  errors.add(:flight_time, "must be equeal or after the today") 
	end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  skip_before_action :authenticate_user!, :only => [:index]
  before_action :set_flight, only: [:show, :edit, :update, :destroy]

  # GET /flights
  # GET /flights.json
  def index
    if !params[:flight].nil?
      @from = params[:flight][:from_airport]
      @to = params[:flight][:to_airport]
      @date = params[:flight][:flight_time]
      @passengers_select = params[:flight][:passengers]
      @flights = Flight.search(@from, @to, @date)

      respond_to do |format|
        format.html
        format.js
      end
    end
  end

  # GET /flights/1
  # GET /flights/1.json
  def show
  end

  # GET /flights/new
  def new
    @flight = Flight.new
  end

  # GET /flights/1/edit
  def edit
  end

  # POST /flights
  # POST /flights.json
  def create
    @flight = Flight.new(flight_params)

    respond_to do |format|
      if @flight.save
        format.html { redirect_to @flight, notice: 'Flight was successfully created.' }
        format.json { render :show, status: :created, location: @flight }
      else
        format.html { render :new }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flights/1
  # PATCH/PUT /flights/1.json
  def update
    respond_to do |format|
      if @flight.update(flight_params)
        format.html { redirect_to @flight, notice: 'Flight was successfully updated.' }
        format.json { render :show, status: :ok, location: @flight }
      else
        format.html { render :edit }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flights/1
  # DELETE /flights/1.json
  def destroy
    @flight.destroy
    respond_to do |format|
      format.html { redirect_to flights_url, notice: 'Flight was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flight
      @flight = Flight.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def flight_params
      params.require(:flight).permit(:airplane_type, :departure_airport_id, :destination_airport_id, :seat_allocation_id, :flight_time)
    end
end

app/helpers/flights_helper.rb
module FlightsHelper
	def seat_available(flight)
		availablity = {}
		flight.seat_configurations.each do |conf| 
			availablity[conf.category] = conf.no_of_rows * conf.seat_in_row - flight.availability
		end
		availablity
	end

	def flight_all_class(flight)
		flight.seat_configurations.map(&:category)
	end

	def flight_price(flight)
		prices = {}
		flight.seat_configurations.each do |conf| 
			prices[conf.category] = conf.price
		end
		prices
	end	

	def format_prices(prices)
		res = ""
		prices.each do |type,price|
			res += "<b>#{type}:</b> Rs #{price} <br>"
		end
		res.html_safe
	end
end

app/views/flights/_flight_form.html.erb
<% if !@flights.nil? %>
    <% if !@flights.empty? %>
        <%= form_tag new_booking_path, method: :get do %>
            <div class="row" id="flights-form">
              <div class="col-md-8 col-md-offset-2" style="margin-top:100px;">
                <table class="table table-striped table-bordered">
                  <thead>
                  <tr>
                    <th></th>
                    <th>Flight ID</th>
                    <th>Date</th>
                    <th>Time</th>
                    <th>Seat Avalaibility</th>
                    <th>Passengers</th>
                    <th>Departure</th>
                    <th>Destination</th>
                    <th>Price</th>
                  </tr>
                  </thead>
                  <tbody>
                  <% @flights.each do |f| %>
                      <tr>
                        <td><%= radio_button_tag(:flight_selected, f.id, checked: f) %></td>
                        <td><%= f.id %></td>
                        <td><%= f.flight_time.strftime("%d/%m/%Y") %></td>
                        <td><%= f.flight_time.strftime("%H:%m") %></td>
                        <td><%= format_availability(seat_available(f)) %></td>
                        <td><%= params[:flight][:passengers] %></td>
                        <td><%= f.from_airport.code %></td>
                        <td><%= f.to_airport.code %></td>
                        <td><%= format_prices(flight_price(f)) %></td>
                      </tr  >
                  <% end %>
                  </tbody>
                </table>
                <%= hidden_field_tag :passenger_count, params[:flight][:passengers] %>
                <%= submit_tag("Book Flight", class: "form-control btn btn-primary btn-block search-btn", id: 'order-btn') %>
              </div>
            </div>
        <% end %>
    
  <% else %>
    <strong> Oopss...No Flights available on selected date and destination.<br>
     Please try with another search.<strong>
  <% end %>
<% end %>

app/views/flights/_form.html.erb
<%= form_with(model: flight, local: true) do |form| %>
  <% if flight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(flight.errors.count, "error") %> prohibited this flight from being saved:</h2>

      <ul>
      <% flight.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :airplane_type %>
    <%= form.text_field :airplane_type %>
  </div>

  <div class="field">
    <%= form.label :departure_airport_id %>
    <%= form.number_field :departure_airport_id %>
  </div>

  <div class="field">
    <%= form.label :destination_airport_id %>
    <%= form.number_field :destination_airport_id %>
  </div>

  <div class="field">
    <%= form.label :seat_allocation_id %>
    <%= form.text_field :seat_allocation_id %>
  </div>

  <div class="field">
    <%= form.label :flight_time %>
    <%= form.datetime_select :flight_time %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/flights/edit.html.erb
<h1>Editing Flight</h1>

<%= render 'form', flight: @flight %>

<%= link_to 'Show', @flight %> |
<%= link_to 'Back', flights_path %>

app/views/flights/index.html.erb
<div id="results" style="display: none;">

</div>

app/views/flights/index.js.erb
$('#results').html("<%= j (render 'flight_form') %>").fadeIn(600);

app/views/flights/new.html.erb
<h1>New Flight</h1>

<%= render 'form', flight: @flight %>

<%= link_to 'Back', flights_path %>

app/views/flights/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Airplane type:</strong>
  <%= @flight.airplane_type %>
</p>

<p>
  <strong>Departure airport:</strong>
  <%= @flight.departure_airport_id %>
</p>

<p>
  <strong>Destination airport:</strong>
  <%= @flight.destination_airport_id %>
</p>

<p>
  <strong>Seat allocation:</strong>
  <%= @flight.seat_allocation_id %>
</p>

<p>
  <strong>Flight time:</strong>
  <%= @flight.flight_time %>
</p>

<%= link_to 'Edit', edit_flight_path(@flight) %> |
<%= link_to 'Back', flights_path %>