config/routes.rb
Rails.application.routes.draw do
  get 'bookings/view_seat'
  get 'bookings/allocate_seat'
  resources :seat_configurations
  resources :passenger_bookings
  resources :passengers
  resources :bookings
  resources :flights
  resources :airports
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  get 'homes/index'
  root "homes#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/passenger.rb
class Passenger < ApplicationRecord
	has_many :passenger_bookings
	has_many :bookings, through: :passenger_bookings
	has_many :flights, through: :bookings

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :name, presence: true
	validates :email, presence: true, format: {with: VALID_EMAIL_REGEX}
end

app/controllers/passengers_controller.rb
class PassengersController < ApplicationController
  before_action :set_passenger, only: [:show, :edit, :update, :destroy]

  # GET /passengers
  # GET /passengers.json
  def index
    @passengers = Passenger.all
  end

  # GET /passengers/1
  # GET /passengers/1.json
  def show
  end

  # GET /passengers/new
  def new
    @passenger = Passenger.new
  end

  # GET /passengers/1/edit
  def edit
  end

  # POST /passengers
  # POST /passengers.json
  def create
    @passenger = Passenger.new(passenger_params)

    respond_to do |format|
      if @passenger.save
        format.html { redirect_to @passenger, notice: 'Passenger was successfully created.' }
        format.json { render :show, status: :created, location: @passenger }
      else
        format.html { render :new }
        format.json { render json: @passenger.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /passengers/1
  # PATCH/PUT /passengers/1.json
  def update
    respond_to do |format|
      if @passenger.update(passenger_params)
        format.html { redirect_to @passenger, notice: 'Passenger was successfully updated.' }
        format.json { render :show, status: :ok, location: @passenger }
      else
        format.html { render :edit }
        format.json { render json: @passenger.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /passengers/1
  # DELETE /passengers/1.json
  def destroy
    @passenger.destroy
    respond_to do |format|
      format.html { redirect_to passengers_url, notice: 'Passenger was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_passenger
      @passenger = Passenger.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def passenger_params
      params.require(:passenger).permit(:name, :email, :dob, :seat_class)
    end
end

app/helpers/passengers_helper.rb
module PassengersHelper
end

app/views/passengers/_form.html.erb
<%= form_with(model: passenger, local: true) do |form| %>
  <% if passenger.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(passenger.errors.count, "error") %> prohibited this passenger from being saved:</h2>

      <ul>
      <% passenger.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :dob %>
    <%= form.datetime_select :dob %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/passengers/edit.html.erb
<h1>Editing Passenger</h1>

<%= render 'form', passenger: @passenger %>

<%= link_to 'Show', @passenger %> |
<%= link_to 'Back', passengers_path %>

app/views/passengers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Passengers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Dob</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @passengers.each do |passenger| %>
      <tr>
        <td><%= passenger.name %></td>
        <td><%= passenger.email %></td>
        <td><%= passenger.dob %></td>
        <td><%= link_to 'Show', passenger %></td>
        <td><%= link_to 'Edit', edit_passenger_path(passenger) %></td>
        <td><%= link_to 'Destroy', passenger, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Passenger', new_passenger_path %>

app/views/passengers/new.html.erb
<h1>New Passenger</h1>

<%= render 'form', passenger: @passenger %>

<%= link_to 'Back', passengers_path %>

app/views/passengers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @passenger.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @passenger.email %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @passenger.dob %>
</p>

<%= link_to 'Edit', edit_passenger_path(@passenger) %> |
<%= link_to 'Back', passengers_path %>