config/routes.rb
Rails.application.routes.draw do
  get 'bookings/view_seat'
  get 'bookings/allocate_seat'
  resources :seat_configurations
  resources :passenger_bookings
  resources :passengers
  resources :bookings
  resources :flights
  resources :airports
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  get 'homes/index'
  root "homes#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/airport.rb
class Airport < ApplicationRecord
	has_many :departed_flights, class_name: 'Flight', foreign_key: :departure_airport_id
	has_many :arriving_flights, class_name: 'Flight', foreign_key: :destination_airport_id
end

app/controllers/airports_controller.rb
class AirportsController < ApplicationController
  before_action :set_airport, only: [:show, :edit, :update, :destroy]

  # GET /airports
  # GET /airports.json
  def index
    @airports = Airport.all
  end

  # GET /airports/1
  # GET /airports/1.json
  def show
  end

  # GET /airports/new
  def new
    @airport = Airport.new
  end

  # GET /airports/1/edit
  def edit
  end

  # POST /airports
  # POST /airports.json
  def create
    @airport = Airport.new(airport_params)

    respond_to do |format|
      if @airport.save
        format.html { redirect_to @airport, notice: 'Airport was successfully created.' }
        format.json { render :show, status: :created, location: @airport }
      else
        format.html { render :new }
        format.json { render json: @airport.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /airports/1
  # PATCH/PUT /airports/1.json
  def update
    respond_to do |format|
      if @airport.update(airport_params)
        format.html { redirect_to @airport, notice: 'Airport was successfully updated.' }
        format.json { render :show, status: :ok, location: @airport }
      else
        format.html { render :edit }
        format.json { render json: @airport.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /airports/1
  # DELETE /airports/1.json
  def destroy
    @airport.destroy
    respond_to do |format|
      format.html { redirect_to airports_url, notice: 'Airport was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_airport
      @airport = Airport.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def airport_params
      params.require(:airport).permit(:name, :code, :address)
    end
end

app/helpers/airports_helper.rb
module AirportsHelper
end

app/views/airports/_form.html.erb
<%= form_with(model: airport, local: true) do |form| %>
  <% if airport.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(airport.errors.count, "error") %> prohibited this airport from being saved:</h2>

      <ul>
      <% airport.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/airports/edit.html.erb
<h1>Editing Airport</h1>

<%= render 'form', airport: @airport %>

<%= link_to 'Show', @airport %> |
<%= link_to 'Back', airports_path %>

app/views/airports/index.html.erb
<h1>Airports</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Code</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @airports.each do |airport| %>
      <tr>
        <td><%= airport.name %></td>
        <td><%= airport.code %></td>
        <td><%= airport.address %></td>
        <td><%= link_to 'Show', airport %></td>
        <td><%= link_to 'Edit', edit_airport_path(airport) %></td>
        <td><%= link_to 'Destroy', airport, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Airport', new_airport_path %>

app/views/airports/new.html.erb
<h1>New Airport</h1>

<%= render 'form', airport: @airport %>

<%= link_to 'Back', airports_path %>

app/views/airports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @airport.name %>
</p>

<p>
  <strong>Code:</strong>
  <%= @airport.code %>
</p>

<p>
  <strong>Address:</strong>
  <%= @airport.address %>
</p>

<%= link_to 'Edit', edit_airport_path(@airport) %> |
<%= link_to 'Back', airports_path %>