config/routes.rb
Rails.application.routes.draw do
  get 'bookings/view_seat'
  get 'bookings/allocate_seat'
  resources :seat_configurations
  resources :passenger_bookings
  resources :passengers
  resources :bookings
  resources :flights
  resources :airports
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  get 'homes/index'
  root "homes#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/passenger_booking.rb
class PassengerBooking < ApplicationRecord
  belongs_to :passenger
  belongs_to :booking
  after_create :generate_pnr, :update_flight_seat_blocker
  after_save :flush_cache_for_flight

	# Class(1) + FlightNumber(3) + PassangerBookingID(4)
	validate :pnr_and_seat_validatation
	def generate_pnr
		pnr = (passenger.seat_class.try(:[], 0) || 'F').to_s + (("%04d" % (booking.flight.id % (1000)))).to_s + ("%04d" % (id % 10000)).to_s
		self.update!(pnr_number: pnr)  
	end

	def update_flight_seat_blocker
		Flight.update_blocked_seats(-1)
	end

	def self.parse_pnr(pnr)
		where(id: pnr[5..8].to_i).first
	end

	def allocate_seat(seat)
	    if PassengerBooking.where(seat_number: seat).find {|b| booking.flight.id == b.booking.flight.id}
	      "Seat #{seat} is booked. Please refresh page and try again"
			else
	      update!(seat_number: seat)
	      nil
	    end
	end

	def self.validate_pnr(pnr, user)
		pb = parse_pnr(pnr)
		pb ? pb.booking.user.id == user : false
	end

	private

	def pnr_and_seat_validatation
		if pnr_number && PassengerBooking.where("pnr_number = ? and id <> ?", pnr_number, id).find {|b| booking.flight.id == b.booking.flight.id}
			errors.add(:pnr_number, "Already Taken") 
		end

		if seat_number && PassengerBooking.where("seat_number = ? and id <> ? ", seat_number, id).find {|b| booking.flight.id == b.booking.flight.id}
			errors.add(:seat_number, "Already Taken") 
		end
	end

	def flush_cache_for_flight
		Rails.cache.delete("Flight_#{booking.flight.id}_map")
	end
end

app/controllers/passenger_bookings_controller.rb
class PassengerBookingsController < ApplicationController
  before_action :set_passenger_booking, only: [:show, :edit, :update, :destroy]

  # GET /passenger_bookings
  # GET /passenger_bookings.json
  def index
    @passenger_bookings = PassengerBooking.all
  end

  # GET /passenger_bookings/1
  # GET /passenger_bookings/1.json
  def show
  end

  # GET /passenger_bookings/new
  def new
    @passenger_booking = PassengerBooking.new
  end

  # GET /passenger_bookings/1/edit
  def edit
  end

  # POST /passenger_bookings
  # POST /passenger_bookings.json
  def create
    @passenger_booking = PassengerBooking.new(passenger_booking_params)

    respond_to do |format|
      if @passenger_booking.save
        format.html { redirect_to @passenger_booking, notice: 'Passenger booking was successfully created.' }
        format.json { render :show, status: :created, location: @passenger_booking }
      else
        format.html { render :new }
        format.json { render json: @passenger_booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /passenger_bookings/1
  # PATCH/PUT /passenger_bookings/1.json
  def update
    respond_to do |format|
      if @passenger_booking.update(passenger_booking_params)
        format.html { redirect_to @passenger_booking, notice: 'Passenger booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @passenger_booking }
      else
        format.html { render :edit }
        format.json { render json: @passenger_booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /passenger_bookings/1
  # DELETE /passenger_bookings/1.json
  def destroy
    @passenger_booking.destroy
    respond_to do |format|
      format.html { redirect_to passenger_bookings_url, notice: 'Passenger booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_passenger_booking
      @passenger_booking = PassengerBooking.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def passenger_booking_params
      params.require(:passenger_booking).permit(:passenger_id, :booking_id)
    end
end

app/helpers/passenger_bookings_helper.rb
module PassengerBookingsHelper
end

app/views/passenger_bookings/_form.html.erb
<%= form_with(model: passenger_booking, local: true) do |form| %>
  <% if passenger_booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(passenger_booking.errors.count, "error") %> prohibited this passenger_booking from being saved:</h2>

      <ul>
      <% passenger_booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :passenger_id %>
    <%= form.number_field :passenger_id %>
  </div>

  <div class="field">
    <%= form.label :booking_id %>
    <%= form.number_field :booking_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/passenger_bookings/edit.html.erb
<h1>Editing Passenger Booking</h1>

<%= render 'form', passenger_booking: @passenger_booking %>

<%= link_to 'Show', @passenger_booking %> |
<%= link_to 'Back', passenger_bookings_path %>

app/views/passenger_bookings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Passenger Bookings</h1>

<table>
  <thead>
    <tr>
      <th>Passenger</th>
      <th>Booking</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @passenger_bookings.each do |passenger_booking| %>
      <tr>
        <td><%= passenger_booking.passenger_id %></td>
        <td><%= passenger_booking.booking_id %></td>
        <td><%= link_to 'Show', passenger_booking %></td>
        <td><%= link_to 'Edit', edit_passenger_booking_path(passenger_booking) %></td>
        <td><%= link_to 'Destroy', passenger_booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Passenger Booking', new_passenger_booking_path %>

app/views/passenger_bookings/new.html.erb
<h1>New Passenger Booking</h1>

<%= render 'form', passenger_booking: @passenger_booking %>

<%= link_to 'Back', passenger_bookings_path %>

app/views/passenger_bookings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Passenger:</strong>
  <%= @passenger_booking.passenger_id %>
</p>

<p>
  <strong>Booking:</strong>
  <%= @passenger_booking.booking_id %>
</p>

<%= link_to 'Edit', edit_passenger_booking_path(@passenger_booking) %> |
<%= link_to 'Back', passenger_bookings_path %>